### ISSUE TITLE
RGB Controll for different status 

### ISSUE THREAD

**Issue by Doprintityourself** [abudden/OctoPrint-USBRelayControl#4]
Hello 
Would like to Love to manage RGB USB Leds to underline the different Status of a printer with color
Cold is blue heating is red Printing is White Pause is yellow  ....
Thanks in advance

**Comment by abudden** [comment]
I think you'd need a different USB device for this, which would require a completely different driver.  I guess you could wire up three relays, one controlling each colour of a non-USB RGB LED, but it's probably better to get something specific.

I don't think this is something I'd want to add to this plugin, but perhaps you could use my plugin (or one or both of the repositories upon which I based my plugin) as a basis for something.  If you based it on https://www.blinkstick.com then it probably wouldn't be too much work.
