### ISSUE TITLE
Unable to activate a button in side bar 

### ISSUE THREAD

**Issue by Flyer74** [abudden/OctoPrint-USBRelayControl#6]
Hello, 

I've been receive my USB relay board. I've been connected it into my Raspberry Pi with octoprint. In SSH I've find the vendor code and the vendor product which are good 16c0 and 05dF. 

I've configure my first action for my Led bar, as ACTIVE : HIGH / DEFAULT : OFF / RELAY No : 1 

I've been restart my RaspberryPi and in the side bar both button ON and OFF are not enable to click it ... 

Any idea ? 

Thanks !

**Comment by abudden** [comment]
Have you set up the udev rules to make sure the user running octoprint has access to the USB device?  If octoprint can't connect to the USB device I think it will grey the buttons out.

**Comment by Flyer74** [comment]
Thanks for your answer, 

I'm trying to edit my udev rules but I don't know exactly how to do that... 

I'm connecting in my raspberry pi via SSH I go into folder etc/udev and I can't go into rules.d (it say to me that there is no directory matching this name ... but LS command show me the directory ...) I open the file 99-com.rules and try to edit and add the line "SUBSYSTEM=="usb", ATTR{idVendor}=="16c0", ATTR{idProduct}=="05df", MODE="777"" but this one is never save on this file ... 

How can I do that ? 

Thanks !!

**Comment by abudden** [comment]
Hi @Flyer74 I must admit this might be getting a bit beyond my skill level to help you, but it sounds like you're trying to edit it as a user rather than as root.  Have you tried using `sudo`, something like:

```
sudo nano /etc/udev/rules.d/99-com.rules
```

and then entering the information into that file?

**Comment by Flyer74** [comment]
Yeah I already do via sudo command but I had never used before nano... 

But after trying another time it is OK all works fine !!! 

Thanks a lot !!!

**Comment by abudden** [comment]
Glad you've got it sorted.
