### ISSUE TITLE
Install fail. Device Privileges

### ISSUE THREAD

**Issue by emerzee1** [abudden/OctoPrint-USBRelayControl#7]
Hi!
I wanted to set the device privileges. I couldn't find the 99-usbrelay.rules file, and I couldn't create it either, due to the denial of root privileges. How can this be done? The plugin does not work without this. Thanks for the help!

**Comment by abudden** [comment]
Did you use `sudo` or `su` when creating the 99-usbrelay.rules file?  It should be just a case of typing something like:

```
nano /etc/udev/rules.d/99-usbrelay.rules
```

**Comment by emerzee1** [comment]
Thank you! Its working!
